mqtt_bridge_node:
  ros__parameters:
    mqtt:
      client:
        protocol: 4      # MQTTv311
      connection:
        host: broker.hivemq.com
        port: 1883
        keepalive: 60
      private_path: device/002
    # serializer: json:dumps
    # deserializer: json:loads
    n_bridges: 12
    bridge:     
      bridge1: ["mqtt_bridge.bridge:RosToMqttBridge","std_msgs.msg:Bool","/ping","AMOS/ping"]
      bridge2: ["mqtt_bridge.bridge:MqttToRosBridge","std_msgs.msg:Bool","AMOS/ping","/pong"]
      bridge3: ["mqtt_bridge.bridge:RosToMqttBridge","std_msgs.msg:String","/echo","AMOS/echo"]
      bridge4: ["mqtt_bridge.bridge:MqttToRosBridge","std_msgs.msg:String","AMOS/echo","/back"]
      bridge5: ["mqtt_bridge.bridge:RosToMqttBridge","std_msgs.msg:String","/private/echo","~/echo"]
      bridge6: ["mqtt_bridge.bridge:MqttToRosBridge","std_msgs.msg:String","~/echo", "/private/back"]
      bridge7: ["mqtt_bridge.bridge:RosToMqttBridge","vda5050_msgs.msg:Connection", "/connection2", "AMOS/v1/TurtleBot/2/connection"]
      bridge8: ["mqtt_bridge.bridge:MqttToRosBridge","vda5050_msgs.msg:Order","AMOS/v1/TurtleBot/2/order","/order2"]
      bridge9: ["mqtt_bridge.bridge:MqttToRosBridge","vda5050_msgs.msg:InstantActions","AMOS/v1/TurtleBot/2/instantActions","/instantActions2"]
      bridge10: ["mqtt_bridge.bridge:RosToMqttBridge","vda5050_msgs.msg:OrderInformation", "/state2", "AMOS/v1/TurtleBot/2/state"]
      bridge11: ["mqtt_bridge.bridge:RosToMqttBridge","vda5050_msgs.msg:Visualization", "/visualization2", "AMOS/v1/TurtleBot/2/visualization"]
      bridge12: ["mqtt_bridge.bridge:MqttToRosBridge","std_msgs.msg:String","AMOS/v1/TurtleBot/2/map","/map2"]

