version: "3"
services:
  fms:
    build: .
    ports:
      - 8080:8080
    volumes:
      - ./maps:/usr/src/app/maps
      - ./config.json:/usr/src/app/config.json
    environment:
      - FMS_DOCKER=1
  mqtt:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
      - 9001:9001